### ISSUE TITLE
Criar apresentação para cada aula.

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#97]
Criar duas apresentações por aula.

- [x] Aula 1 Introdução ao gerenciamento de conteúdo do portal (1h)
  - [x] #99
  - [x] #128
  - [x] ~~Criar slides aula 1~~ #141
- [x] Aula 2 Criação de pasta e página (1h)
  - [x] Teoria Aula 2 (create-page.md)
  - [x] #138
  - [x] ~~Criar slides aula 2~~ #141 
- [x] Aula 3 Criação de notícia (1h)
  - [x] Teoria Aula 3 (create-news.md)
  - [x] #139
  - [x] ~~Criar slides aula 3~~ #141
